question_data =  [
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Animals",
            "question": "You can tell the age of a ladybird by counting the spots on his back.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Animals",
            "question": "Hyenas are more closely related to cats than to dogs.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Animals",
            "question": "Finnish Lapphund dogs were used for herding reindeer.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Animals",
            "question": "Zebras are white with black stripes.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Animals",
            "question": "A caterpillar has more muscles than humans do.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Animals",
            "question": "Otters have pockets under their arms for carrying their favourite snacks and rocks.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Animals",
            "question": "The freshwater amphibian, the Axolotl, can regrow it&#039;s limbs.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Animals",
            "question": "In 2016, the IUCN reclassified the status of Giant Pandas from endangered to vulnerable.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Animals",
            "question": "A slug&rsquo;s blood is green.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Animals",
            "question": "Sea sponges can have hearts.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
    ]

